### PR TITLE
Message forward

### PR DESCRIPTION
**Pull request by su-chang**

### CODE REVIEW

**Comment by huan** [comment]
Could you please create an issue for adding message forward task, and then link everything together to let us have a clear view and summary for all ongoing PR s?

Thank your very much.

**Comment by su-chang** [comment]
Related issue: https://github.com/wechaty/wechaty-puppet-service/issues/135

**Review by windmemory — APPROVED** [review]
Looks good to me, approved!

**Comment by huan** [comment]
Thank you very much for adding this great feature to our puppet service!

It would be great if you can create a PR to update the master branch as well, thank you very much, have a nice weekend!

**Pull request merged**
